Fix undefined action in interpretor
I faced an edge case where action is undefined.
I could not replicate it successfully but found a workaround
to check if action is defined before calling rejected on action.

This error only comes up when I am running Jest on a code where
Future.parallel is used and there are two rejected futures.

Error:
fluture/index.js:155
settle(action.rejected(x));
             ^
TypeError: Cannot read property 'rejected' of undefined